FROM node:18.14.2 AS builder
RUN mkdir -p /app
WORKDIR /app
ADD . .

RUN npm install
RUN npm run build

ARG STAGE
ENV STAGE ${STAGE}

ARG PORT
ENV PORT ${PORT}
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}


ARG MONGODB_URI
ENV MONGODB_URI ${MONGODB_URI}
ARG JWT_SECRET
ENV JWT_SECRET ${JWT_SECRET}
ARG ACCESS_TOKEN_EXPIRY
ENV ACCESS_TOKEN_EXPIRY ${ACCESS_TOKEN_EXPIRY}


CMD npm run start:prod